server.servlet.contextPath: /challenge
resilience4j:
  ratelimiter:
    instances:
      calculatorService:
        limit-for-period: 3
        limit-refresh-period: 60s
        timeout-duration: 0
  circuitbreaker:
    instances:
      percentageProvider:
        waitDurationInOpenState: 1800s
        minimumNumberOfCalls: 3

provider:
  url: https://api.mockfly.dev/mocks/6db02e4d-880e-4f21-8f13-2d7dfec11a3f

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://pgsql:5432/tenpo-challenge
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

retry:
  maxAttempts: 3
  delay: 1000