server.servlet.contextPath: /challenge
resilience4j.ratelimiter:
  instances:
    calculatorService:
      limit-for-period: 3
      limit-refresh-period: 60s
      timeout-duration: 0

logging:
  level:
    io:
      github:
        resilience4j: TRACE
provider:
  url: https://api.mockfly.dev/mocks/6db02e4d-880e-4f21-8f13-2d7dfec11a3f